Fix Windows build
Not sure how this slipped passed us. Could be Windows 10 specific, but
there were several errors that are now fixed:
* Error C2131: expression did not evaluate to a constant
* Error C2679: binary '<<': no operator found which takes a right-hand
operand of type 'const std::string' (or there is no acceptable
conversion)

To use std::min we need to undefine macros on Windows, which we now do
in platform.h

Note: It still has 48 warnings on Windows that are not fixed because
      the code is currently being mostly rewritten in another branch.
* warning C4018: '<': signed/unsigned mismatch
* warning C4099: 'RetroResource::BitmapCollection': type name first
  seen using 'struct' now seen using 'class'